### ISSUE TITLE
Campaign resource does not appear to support limit or offset

### ISSUE THREAD

**Issue by krypterro** [plivo/plivo-python#204]
The docs say:

>"To list all resources, you can simply use the following pattern that will handle the pagination for you automatically, so you won't have to worry about passing the right limit and offset values."

```python
for resource in client.resources:
    print(resource.id)
```

However, when we try this with the campaign resource with this code:

```python
import plivo

auth_id = '*************'
auth_token = '*********************'

def main():
    client = plivo.RestClient(auth_id=auth_id, auth_token=auth_token)
    for resource in client.campaign:
        print(resource)
        
main()
```

We get the following error:
```
Traceback (most recent call last):
  File "/home/krypterro/PyApps/cbplivo/get_campaigns_test.py", line 13, in <module>
    main()
  File "/home/krypterro/PyApps/cbplivo/get_campaigns_test.py", line 10, in main
    for resource in client.campaign:
  File "/home/krypterro/PyApps/cbplivo/.venv/lib/python3.8/site-packages/plivo/base.py", line 238, in gen
    response = self.list(limit=limit, offset=offset)
TypeError: list() got an unexpected keyword argument 'limit'
```

Does the campaign resource not support limit and/or offset, or are we doing something wrong here?

**Comment by huzaif-plivo** [comment]
@krypterro Thank you for your input. You are correct! As of currently, the campaign resource does not allow offset and limit. Since the product is currently in Beta, we are working to improve it, and we have noted this issue to be addressed in future updates. In case if you have any other concerns, please feel free to reach out to our [support team](https://support.plivo.com/hc/en-us)
