### ISSUE TITLE
AttributeError: 'module' object has no attribute 'RestClient'

### ISSUE THREAD

**Issue by paulgiordano** [plivo/plivo-python#47]
Using the example code:

```
import plivo

client = plivo.RestClient('xxxx', 'yyyy')
try:
  response = client.messages.create(
    src='1630zzzzzzzz',
    dst='1630qqqqqqq',
    text='Hello, world!',
  )
  print(response.__dict__)
except plivo.exceptions.PlivoRestError as e:
    print(e)

```

receive:
```
Traceback (most recent call last):
  File "plivo.py", line 1, in <module>
    import plivo
  File "/home/gio/plivo.py", line 3, in <module>
    client = plivo.RestClient('xxxxxx', 'yyyyyy')
AttributeError: 'module' object has no attribute 'RestClient'

```

Pretty much a direct copy from your site.

**Comment by nixonsam** [comment]
@paulgiordano as @Harmon758 mentioned, This is happening as the Python script/module is named as `plivo.py`

Which in turn is attempting to import the file itself as a module instead of the Plivo package. 
Closing this issue, feel free to contact support if you need any assistance or in case of any concerns.
